version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.0.6
  aws-ecr: circleci/aws-ecr@1.0.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'nginx'
          tag: '${CIRCLE_SHA1}'

      - aws-ecs/deploy-service-update:
                requires:
                  - aws-ecr/build_and_push_image
                family: 'nginx-sample-webapp'
                cluster-name: 'nginx-sample-cluster'
                container-image-name-updates: 'container=nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx:${CIRCLE_SHA1}'